apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  params:
    - name: DEPLOYMENT
      type: string
    - name: IMAGE
      type: string
  steps:
    - name: oc-deploy
      image: quay.io/openshift/origin-cli:latest
      script: |
        oc set image deployment/$(params.DEPLOYMENT) *=$(params.IMAGE) --record
