apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: microservice-cd-pipeline
spec:
  params:
    - name: IMAGE
      type: string
    - name: DEPLOYMENT
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: lint
      taskRef:
        name: lint-task
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace

    - name: test
      runAfter: [lint]
      taskRef:
        name: test-task
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace

    - name: build
      runAfter: [test]
      taskRef:
        name: build-task
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace

    - name: deploy
      runAfter: [build]
      taskRef:
        name: deploy-task
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: DEPLOYMENT
          value: $(params.DEPLOYMENT)
