apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: microservice-cd-pipelinerun
  namespace: sn-labs-yadavnitesh2
spec:
  pipelineRef:
    name: microservice-cd-pipeline
  params:
    - name: IMAGE
      value: us.icr.io/sn-labs-yadavnitesh2/ci-cd-final-project:latest
    - name: DEPLOYMENT
      value: ci-cd-final-deployment
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: shared-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
